version: "3"

services:
  rocketpay-postgres-db:
    image: postgres:12.4-alpine
    container_name: rocketpay-postgres-db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
